version: "3.9"
services:
  web:
    image: "nextcloud:24.0.10"
    restart: always
    volumes:
      - "./nextcloud-data:/var/www/html:rw"
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_HOST: postgresql  
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    container_name: nextcloud-postgresql
    image: "postgres:14.7-alpine"
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    volumes:
      - "./postgres-data:/var/lib/postgresql/data:rw"
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "-U", "${PSQL_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5